/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val miFraccion = Fraccion(5, 3) 

    print("Mi fracción es: ")
    miFraccion.mostrar() 
    println("numerador: ${miFraccion.numerador}") 
    println("denominador: ${miFraccion.denominador}")
}

